config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  root "home#index"
  resource :test_partial, only: [:create]
  resource :test_view_component, only: [:create, :show]
  resource :workaround, only: [:create]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
end

app/controllers/test_partials_controller.rb
class TestPartialsController < ApplicationController
  def create
    render partial: "test_partials/create"
  end
end

app/controllers/test_view_components_controller.rb
class TestViewComponentsController < ApplicationController
  def create
    render PostUsingViewComponent.new
  end

  def show
    render GetUsingViewComponent.new
  end
end

app/controllers/workarounds_controller.rb
class WorkaroundsController < ApplicationController
  def create
    render WorkaroundComponent.new, content_type: "text/html"
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/home/index.html.erb
<h1>Using partial</h1>

<turbo-frame id="using_partial" style="border: 1px solid red; padding: 1rem;">
  Partial turbo frame
</turbo-frame>

<div style="margin-top: 2rem;">
  <%= form_with(method: :post, url: test_partial_path, data: { "turbo-frame": "using_partial" }) do |form| %>
    <%= form.submit "Update turbo frame with POST" %>
  <% end %>
</div>

<hr>

<h1>Using ViewComponent (POST)</h1>

<turbo-frame id="post_using_view_component" style="border: 1px solid red; padding: 1rem;">
  View component turbo frame
</turbo-frame>

<div style="margin-top: 2rem;">
  <%= form_with(method: :post, url: test_view_component_path, data: { "turbo-frame": "post_using_view_component" }) do |form| %>
    <%= form.submit "Update turbo frame with POST" %>
  <% end %>
</div>

<hr>

<h1>Using ViewComponent (GET)</h1>

<turbo-frame id="get_using_view_component" style="border: 1px solid red; padding: 1rem;">
  View component turbo frame
</turbo-frame>

<div style="margin-top: 2rem;">
  <%= form_with(method: :get, url: test_view_component_path, data: { "turbo-frame": "get_using_view_component" }) do |form| %>
    <%= form.submit "Update turbo frame with GET" %>
  <% end %>
</div>

<hr>

<h1>Workaround (POST + text/html content type)</h1>

<turbo-frame id="workaround" style="border: 1px solid red; padding: 1rem;">
  View component turbo frame
</turbo-frame>

<div style="margin-top: 2rem;">
  <%= form_with(method: :post, url: workaround_path, data: { "turbo-frame": "workaround" }) do |form| %>
    <%= form.submit "Update turbo frame with POST" %>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ViewComponent</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application" %>
    <script type="module">
      import hotwiredTurbo from 'https://cdn.skypack.dev/@hotwired/turbo';
    </script>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/test_partials/_create.html.erb
<turbo-frame id="using_partial">
  Partial turbo frame updated using POST
</turbo-frame>